apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-be
  template:
    metadata:
      labels:
        app: insurance-be
    spec:
      containers:
        - name: springboot-container
          image: rafifsulaiman/darkweb:REPLACE_ME_TAG
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL_PROD
              valueFrom:
                configMapKeyRef:
                  name: insurance-be-config
                  key: DATABASE_URL_PROD
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: insurance-be-config
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insurance-be-secret
                  key: DATABASE_PASSWORD